{
    "TotalEventCount":3,
    "1":{
        "Date":"10/06/22",
        "Day":"THURSDAY",
        "Time":"08:00 AM",
        "Location":"ESCONDIDO",
        "Cost":"$30",
        "TotalPlayers":"22",
        "PlayersIn":[],
        "PlayersInvited":[],
        "PlayersPaid":[
            85,
            91,
            121,
            122
        ],
        "Dark":{
            "Goalie":[
                122
            ],
            "Line1":{
                "Forward":[
                    85
                ],
                "Defense":[]
            },
            "Line2":{
                "Forward":[
                    121
                ],
                "Defense":[
                    85
                ]
            }
        },
        "Light":{
            "Goalie":[],
            "Line1":{
                "Forward":[],
                "Defense":[
                    91
                ]
            },
            "Line2":{
                "Forward":[],
                "Defense":[]
            }
        },
        "Status":"Current"
    },
    "2":{
        "Date":"10/08/22",
        "Day":"SATURDAY",
        "Time":"05:00 AM",
        "Location":"POWAY",
        "Cost":"$30",
        "TotalPlayers":"22",
        "PlayersIn":[],
        "PlayersInvited":[],
        "PlayersPaid":[],
        "Dark":{
            "Goalie":[],
            "Line1":{
                "Forward":[],
                "Defense":[]
            },
            "Line2":{
                "Forward":[],
                "Defense":[]
            }
        },
        "Light":{
            "Goalie":[],
            "Line1":{
                "Forward":[],
                "Defense":[]
            },
            "Line2":{
                "Forward":[],
                "Defense":[]
            }
        },
        "Status":"Current"
    },
    "3":{
        "Date":"10/07/22",
        "Day":"FRIDAY",
        "Time":"08:00 AM",
        "Location":"ESCONDIDO",
        "Cost":"$30",
        "TotalPlayers":"22",
        "PlayersIn":[],
        "PlayersInvited":[],
        "PlayersPaid":[
            85
        ],
        "Dark":{
            "Goalie":[],
            "Line1":{
                "Forward":[
                    85
                ],
                "Defense":[
                    91
                ]
            },
            "Line2":{
                "Forward":[],
                "Defense":[]
            }
        },
        "Light":{
            "Goalie":[],
            "Line1":{
                "Forward":[],
                "Defense":[]
            },
            "Line2":{
                "Forward":[],
                "Defense":[]
            }
        },
        "Status":"Current"
    }
}